name: Production build

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Yarn cache
        uses: c-hive/gha-yarn-cache@v1
      
      - name: Install dependencies using Yarn
        run: yarn install
      
      - name: Generate GraphQL types based on the schema 
        run: yarn apollo-gen
      
      - name: Build the app
        run: yarn build

      - name: Archive Staging artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: build
      - name: Apply Firebase target
        uses: w9jds/firebase-action@master
        with:
          args: target:apply hosting production-website production-el1flem-pdlb
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: "deploy --only hosting: production-website"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
